Repository Developer-Student-Clubs-UBa/hactoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#27 feat: added rupali-codes as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#23 Task1
  README.md
  Task1/README.md
  Task1/intro.json
  Task2/README.md
Labels: hacktoberfest-accepted

#55 feat: added Abdulkbk as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#51 feat: added shubh045 socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#60 feat: added shruti0419 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#62 feat: added renanlmiranda as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#40 feat: added my techstack - imyogeshgaur
  Task4/techStack.html
Labels: hacktoberfest-accepted

#61 feat: added my techstack - Nyong Godwill
  Task4/techStack.html
Labels: hacktoberfest-accepted

#52 feat: added my techstack - renanlmiranda
  Task4/techStack.html
Labels: hacktoberfest-accepted

#63 feat: added sudiptapradhan as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#30 feat: added my techstack - rupali-codes
  Task4/techStack.html
Labels: hacktoberfest-accepted

#64 feat: added educational background of jeremie1112
  Task3/education.py
Labels: hacktoberfest-accepted

#36 feat: added my techstack - yokwejuste
  Task4/techStack.html
Labels: hacktoberfest-accepted

#65 feat: added manjusha2912 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#59 feat: added educational background of Nyong Godwill
  Task3/education.py
Labels: hacktoberfest-accepted

#53 feat: added educational background of shubh045
  Task3/education.py
Labels: hacktoberfest-accepted

#50 feat: added educational background of renanlmiranda
  Task3/education.py
Labels: hacktoberfest-accepted

#38 feat: added imyogeshgaur socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#24 feat: added educational background of iamhariom0228
  Task3/education.py
Labels: hacktoberfest-accepted

#29 feat: added educational background of rupali-codes
  Task3/education.py
Labels: hacktoberfest-accepted

#69 Adding my username Aravindhsiva as Contributor
  Task1/intro.json
Labels: help wanted

#71 feat: add my techstack - Fienne
  Task4/techStack.html
Labels: hacktoberfest-accepted

#39 feat: added educational background ofimyogeshgaur
  Task3/education.py
Labels: hacktoberfest-accepted

#22 feat: added JYDP02 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#74 CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, hacktoberfest-accepted

#70 feat: add educational background of Fienne
  Task3/education.py
Labels: hacktoberfest-accepted

#68 feat : add socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#82 task 1 contribution
  Task1/intro.json
Labels: hacktoberfest-accepted

#83 feat: added Abdulkbk socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#86 feat: added ola-nishant socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#88 feat: added amanfangeria980 socials
  Task1/intro.json
Labels: hacktoberfest-accepted

#85 feat: added educational background of Abdulkbk
  Task3/education.py
Labels: hacktoberfest-accepted

#89 feat: added contributors images to the repo
  README.md
Labels: hacktoberfest-accepted

#79 feat: added MR-DHRUV as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#90 feat: added spykelionel as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#92 feat: added amanfangeria980 as contributor
  Task2/socials.js
Labels: hacktoberfest-accepted

#96 feat: added educational background of ola-nishant
  Task3/education.py
Labels: hacktoberfest-accepted

#95 feat: added manjusha291 socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#94 Update intro.json
  Task1/intro.json
Labels: hacktoberfest-accepted

#101 feat: added amanfangeria980 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#97 feat: added educational background of spykelionel
  Task3/education.py
Labels: hacktoberfest-accepted

#103 feat: Added social media handles for burnleydev1
  Task2/socials.js
Labels: hacktoberfest-accepted

#104 feat: added my techstack ola-nishant
  Task4/techStack.html
Labels: hacktoberfest-accepted

#93 Add socials of spykelionel
  Task2/socials.js
Labels: hacktoberfest-accepted

#110 feat: Added Burnleydev1 tech_stack
  Task4/techStack.html
Labels: hacktoberfest-accepted

#109 feat: xennia316 as contributor and maintainer
  Task1/intro.json
Labels: hacktoberfest-accepted

#107 feat: added my techstack - spykelionel
  Task4/techStack.html
Labels: hacktoberfest-accepted

#111 feat: added baimamboukar as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#105 feat: Added education details burnleydev1
  Task3/education.py
Labels: hacktoberfest-accepted

#112 feat: added DibyajitTripathy as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#108 feat: added educational background of amanfangeria980
  Task3/education.py
Labels: hacktoberfest-accepted

#106 feat: added baimamboukar as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#113 feat: added my techstack - amanfangeria980
  Task4/techStack.html
Labels: hacktoberfest-accepted

#115 feat: added baimamboukar socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#116 feat: added DibyajitTripathy socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#117 feat: added educational background of baimamboukar
  Task3/education.py
Labels: hacktoberfest-accepted

#119 feat: added Kshitij Verma as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#118 feat: added educational background of DibyajitTripathy
  Task3/education.py
Labels: hacktoberfest-accepted

#122 feat: added my techstack - DibyajitTripathy
  Task4/techStack.html
Labels: hacktoberfest-accepted

#121 feat: added MR-DHRUV socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#124 feat: added Kshitij Verma's socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#125 feat: added educational background of MR-DHRUV
  Task3/education.py
Labels: hacktoberfest-accepted

#127 feat: added my techstack - MR-DHRUV
  Task4/techStack.html
Labels: hacktoberfest-accepted

#130 feat: added educational background of Kshitij Verma
  Task3/education.py
Labels: hacktoberfest-accepted

#131 feat: added andrew21-mch as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#133 updated file in Intro.js
  Task1/intro.json
Labels: hacktoberfest-accepted

#135 feat: added my Techstack - kshitijv256
  Task4/techStack.html
Labels: hacktoberfest-accepted

#136 feat: added andrew21-mch socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#134 Update intro.json
  Task1/intro.json
Labels: hacktoberfest-accepted

#138 Update intro.json
  Task1/intro.json
Labels: hacktoberfest-accepted

#128 feat: added my techstack - Abdulkbk
  Task4/techStack.html
Labels: hacktoberfest-accepted

#141 feat: added educational background of Joydeep Mallick
  Task3/education.py
Labels: hacktoberfest-accepted

#139 feat: added andrew21-mch education
  Task3/education.py
Labels: hacktoberfest-accepted

#144 feat: added impetus007 socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#145 Task1
  Task1/intro.json
Labels: hacktoberfest-accepted

#147 Update intro.json
  Task1/intro.json
Labels: hacktoberfest-accepted

#149 feat: added Kshitij-10 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#148 Added Vansh-Goel as the contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#152 Update socials.js
  Task2/socials.js
Labels: hacktoberfest-accepted

#151 feat: added lando-paul as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#157 feat added fisher monk as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#167 feat: added techstack lando-paul
  Task4/techStack.html
Labels: hacktoberfest-accepted

#166 feat: added fisher monk socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#156 feat: added impetus007 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#169 feat: added fish monk educational background
  Task3/education.py
Labels: hacktoberfest-accepted

#160 feat: added my techstack - Kshitij-10
  Task4/techStack.html
Labels: hacktoberfest-accepted

#172 feat: added y0kw3ju5t3 tech stack
  Task4/techStack.html
Labels: hacktoberfest-accepted

#163 feat: added educational backgroud - lando-paul
  Task3/education.py
Labels: hacktoberfest-accepted

#161 feat: added lando-paul socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#174 Update intro.json
  Task1/intro.json
Labels: hacktoberfest-accepted

#146 feat: added educational background of Joydeep Mallick
  Task1/intro.json
Labels: hacktoberfest-accepted

#162 Update education.py
  Task3/education.py
Labels: hacktoberfest-accepted

#153 feat: added Kshitij-10 socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#155 feat: added educational background of Kshitij-10
  Task3/education.py
Labels: hacktoberfest-accepted

#168 Update intro.json
  Task1/intro.json
Labels: hacktoberfest-accepted

#158 Update intro.json
  Task1/intro.json
Labels: hacktoberfest-accepted

#175 Update socials.js
  Task2/socials.js
Labels: hacktoberfest-accepted

#176 del: removed draft PR illustration
  README.md
Labels: hacktoberfest-accepted

#181 feat: added yokwejuste as maintainer
  Task1/intro.json
Labels: hacktoberfest-accepted

#182 feat: added my socials - yokwejuste
  Task2/socials.js
Labels: hacktoberfest-accepted

#183 feat: added yokwejuste educational background
  Task3/education.py
Labels: hacktoberfest-accepted

#184 feat: added <Mahir> socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#185 feat: added my techstack - yokwejuste
  Task4/techStack.html
Labels: hacktoberfest-accepted

#187 feat: added adrzxxx as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#189 feat: added mritul as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#203 feat: added my techstack - hrishikesh-g
  Task4/techStack.html
Labels: hacktoberfest-accepted

#202 feat: added educational background of adrzxxx
  Task3/education.py
Labels: hacktoberfest-accepted

#201 feat:added VaibhavArora314 education background
  Task3/education.py
Labels: hacktoberfest-accepted

#200 feat: added educational background of hrishikesh-g
  Task3/education.py
Labels: hacktoberfest-accepted

#194 feat: added VaibhavArora314 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#199 feat: added VaibhavArora314 socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#198 feat: added educational background of mritul
  Task3/education.py
Labels: hacktoberfest-accepted

#197 feat: added mritul socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#196 added codedrian as a contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#205 feat: added my techstack - VaibhavArora314
  Task4/techStack.html
Labels: hacktoberfest-accepted

#195 feat: added socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#207 Task 1
  Task1/intro.json
Labels: hacktoberfest-accepted

#192 feat: added socials
  Task2/socials.js
Labels: hacktoberfest-accepted

#191 Update README.md
  Task1/README.md
Labels: hacktoberfest-accepted

#206 feat: added Divyanshi2408 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#213 feat: added Ngong Marcel as a contributor and maintainer
  Task1/intro.json
Labels: hacktoberfest-accepted

#211 feat: added my techstack - mritul
  Task4/techStack.html
Labels: hacktoberfest-accepted

#210 Update socials.js
  Task2/socials.js
Labels: hacktoberfest-accepted

#214 feat: added yashg-116 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#215 Update education.py
  Task3/education.py
Labels: hacktoberfest-accepted

#217 feat: added Nandini-13 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#218 Task2
  Task2/socials.js
Labels: hacktoberfest-accepted

#222 Update intro.json
  Task1/intro.json
Labels: hacktoberfest-accepted

#221 feat: added madhavgupta07 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#220 feat: added educational background of yashg-116
  Task3/education.py
Labels: hacktoberfest-accepted

#223 Task4
  Task4/techStack.html
Labels: hacktoberfest-accepted

#226 I just added my details
  Task1/intro.json
Labels: hacktoberfest-accepted

#229 feat: added haziq ali as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#230 feat: added Ansh1693 as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#231 Just added my social handles
  Task2/socials.js
Labels: hacktoberfest-accepted

#232 feat: added Ansh1693 socials
  Task1/README.md
  Task1/intro.json
  Task2/socials.js
  Task3/education.py
  Task4/techStack.html
Labels: hacktoberfest-accepted

#228 added raj-hero as contributer
  Task1/intro.json
  Task4/techStack.html
Labels: hacktoberfest-accepted

#234 Added my educational experience
  Task3/education.py
Labels: hacktoberfest-accepted

#239 feat: added kartikkc as contributor
  Task1/intro.json
Labels: hacktoberfest-accepted

#241 Added Education details
  Task3/education.py
Labels: hacktoberfest-accepted

#240 Completed Task 1
  Task1/intro.json
Labels: hacktoberfest-accepted

#251 feat: : Added contributor and maintainer
  Task1/intro.json
Labels: hacktoberfest-accepted

#247 Added techstack for isaiah-0914
  Task4/techStack.html
Labels: hacktoberfest-accepted

#252 feat: added my techstack - JoydeepMallick
  Task4/techStack.html
Labels: hacktoberfest-accepted

#255 feat: added my techstack - renanlmiranda
  Task4/techStack.html
Labels: hacktoberfest-accepted

#259 feat: added educational background of renanlmiranda
  Task3/education.py
Labels: hacktoberfest-accepted

#265 Completed all 4 tasks
  Task1/intro.json
  Task2/socials.js
  Task3/education.py
  Task4/techStack.html
Labels: hacktoberfest-accepted

#277 Update socials.js
  Task2/socials.js
Labels: hacktoberfest-accepted
